// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxwubiiidifurbcevgah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14d3ViaWlpZGlmdXJiY2V2Z2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NzgyNjUsImV4cCI6MjA2NzQ1NDI2NX0.QZaDpkLVKvuQCkCZD3UwAzfN4Rebkbh9e-v_KdYmtYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});